// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzrV4IjSy7se7-IllDWUbZasTv4P359lw',
    appId: '1:885389546102:web:f4b8efcf2a24f3e1bb0557',
    messagingSenderId: '885389546102',
    projectId: 'aneka-belut',
    authDomain: 'aneka-belut.firebaseapp.com',
    storageBucket: 'aneka-belut.appspot.com',
    measurementId: 'G-7D8V4T7CL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd0HjPhdXloO18BHtscWyX8tyB-Mbrp0o',
    appId: '1:885389546102:android:f38a96a0ac9d5898bb0557',
    messagingSenderId: '885389546102',
    projectId: 'aneka-belut',
    storageBucket: 'aneka-belut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKFm9T4KQvQdsagEDmw1Lxg8G0DRlPsY',
    appId: '1:885389546102:ios:4eb235ce8d73df3bbb0557',
    messagingSenderId: '885389546102',
    projectId: 'aneka-belut',
    storageBucket: 'aneka-belut.appspot.com',
    iosBundleId: 'com.ncodeslab.neews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKFm9T4KQvQdsagEDmw1Lxg8G0DRlPsY',
    appId: '1:885389546102:ios:86c2e0aee051b501bb0557',
    messagingSenderId: '885389546102',
    projectId: 'aneka-belut',
    storageBucket: 'aneka-belut.appspot.com',
    iosBundleId: 'com.example.neews',
  );
}
